version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./vendor:/app/vendor
      - ./public:/app/public
      - .:/var/www/html